### ISSUE TITLE
Add support for generating a higher resolution diagram image for PDF export

### ISSUE THREAD

**Issue by mflorea** [xwikisas/application-diagram#103]
The diagram image generated automatically for PDF export doesn't scale when you do a large print. It should be possible for control the image quality (resolution / DPI) per diagram.

**Comment by mflorea** [comment]
One solution that @oanalavinia and I discussed is to add a new integer property ``pdfImageExportZoom`` to the ``DiagramClass`` that specifies the zoom to apply to the diagram before generating the image that will be used for PDF export. The default value would be 100% (no zoom). A bigger zoom (e.g. 400%) will generate a bigger image with a better quality (resolution).

**Comment by oanalavinia** [comment]
As a conclusion, for modifying the quality of the image-based XWiki PDF Export (see #102) a diagram must be edited in object mode for modifying pdfImageExportZoom property.
As is pointed in the hint of the property, the zoom must be a number (>0). A value larger than 5 might bring very little extra value.

**Comment by ane-gabriela** [comment]
More info as tested on Chrome 81, Firefox 75 and IE 11:

- there is a big clear difference between the zoom of 1 and 2
- the zoom for 2,3,4,5 changes very slightly the text clarity and thickness
