### ISSUE TITLE
Add support for disabling the features that require an external server

### ISSUE THREAD

**Issue by mflorea** [xwikisas/application-diagram#105]
For those that are concerned about privacy, it should be possible to disable the features that require an external server. For this we could add a boolean (checkbox) configuration option in the Diagram administration section: "Disable features requiring an external server".

ATM this would affect the PDF export (from the diagram editor) and the image export (on IE11 only).

**Comment by oanalavinia** [comment]
Now features that require an external server can be disabled from Diagram Config page (disableExternalServices option, which defaults to False)

As a result, by disabling it, a pop-up will be shown for export as pdf from diagram editor, or when exporting as png / jpeg in IE browser.
