### ISSUE TITLE
Paths to images inserted into diagrams become invalid at upgrade

### ISSUE THREAD

**Issue by aifrimxwiki** [xwikisas/application-diagram#11]
When adding an image to a diagram, the path of the image is created with the current version of the application. 
<domainname>/xwiki/webjars/wiki%3Axwiki/draw.io/**8.9.9**/img/clipart/Gear_128x128.png
Steps to reproduce:
* create a new diagram
* select More shapes, check Clipart and click "Apply"
* open "Clipart / Computer" (or any other Clipart category) and add an image to your diagram

Result:
* at an upgrade, the image becomes unreachable unless manually updating the path. 
![wrongimagepath](https://user-images.githubusercontent.com/370535/52572627-e528d380-2e20-11e9-8e9f-435bd3dcdb5b.png)

Expected result:
* the images are properly displayed after the upgrade
![correctimagepath](https://user-images.githubusercontent.com/370535/52572633-e823c400-2e20-11e9-929a-1ec5fa17a12f.png)

**Comment by mflorea** [comment]
Many of the shapes you can insert into a diagram are images loaded from the draw.io WebJar. The problem is that the WebJar URL includes the WebJar version so the URLs of all these shapes include the WebJar version. Upgrading the WebJar version breaks the shapes from the existing diagrams.

**Comment by oanalavinia** [comment]
For this fix to be applied in the context of a diagram an edit step it is needed (for updating the sources). Meaning that upgrading an older version to 1.9 will still be showing a link to the migration script. But for diagrams created or edited stating with 1.9 there is no additional step required.
