### ISSUE TITLE
The label of internal links is duplicated when exporting a diagram to PDF via the XWiki export

### ISSUE THREAD

**Issue by slauriere** [xwikisas/application-diagram#120]
## Steps to reproduce

* Add a labeled link to a diagram toward an internal wiki page (data:xwiki/reference).
* Export the diagram via XWiki > More actions > Export > PDF

## Actual vs expected result

The link label shows up three times in the created PDF instead of once.

**Comment by oanalavinia** [comment]
The link is added using directly _Insert -> Link.._ (the + button on top of the editor), or is applied on a piece of text?

**Comment by js-ddev** [comment]
Hi, we heard about this issue by selecting a piece of text, then click on the "insert link" button in the layout panel on the right.
(a third method would be select a piece of text and right click on it to insert a link, but it was not was has been done here).

**Comment by snazare** [comment]
can not reproduce on xwiki 15.10.10, diagram pro 1.20.5 neither by adding a link to a piece of text or by clicking in Insert -> Link.
