### ISSUE TITLE
Text not marked as containing link to another page/website in XWiki PDF export

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#129]
Steps to reproduce:

1. Create a new Diagram
2. Add some shapes
3. Add a word in each shape
4. Select the word from one of the shapes
5. Click on the Link... button below Insert from the right panel
6. Select a wiki page > Apply
7. Select another shape/word
8. Click on the Link... button below Insert from the right panel
9. Select External and paste an URL eg. https://en.wikipedia.org/wiki/Flower
10. Click Save & View
11. Access More actions > Export > Export as PDF
12. Deselect all options > Export

Expected results: Text is marked as containing links to internal/external pages.

Actual results: Text is not marked but when hover the links are there.

Environment: Windows 10, XWiki 11.10.4 with MySQL 5.7 and Chrome 80

![ViewMode](https://user-images.githubusercontent.com/40691112/78346430-b5e6a000-75a7-11ea-8867-1df5ccdfb868.jpg)
![LinkToSandbox](https://user-images.githubusercontent.com/40691112/78346433-b67f3680-75a7-11ea-87a0-081cbf3fee10.jpg)
[xwiki_Diagram_User+1+Diagram_WebHome.pdf](https://github.com/xwikisas/application-diagram/files/4426199/xwiki_Diagram_User%2B1%2BDiagram_WebHome.pdf)

**Comment by oanalavinia** [comment]
This reason for this issue is that the style of a link (underline and blue color) was not added in #101 (note that the links are working)
