### ISSUE TITLE
Downloading SVG makes the internal links non functional

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#130]
Steps to reproduce:

1. Create a new Diagram
2. Add some shapes
3. Add a word in each shape
4. Select the word from one of the shapes
5. Click on the Link... button below Insert from the right panel
6. Select a wiki page > Apply
7. Select another shape/word
8. Click on the Link... button below Insert from the right panel
9. Select External and paste an URL eg. https://en.wikipedia.org/wiki/Flower
10. Click File > Export as > SVG...
11. Click on Export
12. Click on Download
13. Open the SVG

Expected results: The links are showing as expected.

Actual results: The links to internal pages aren't showing properly eg. "file:///C:/xwiki/bin/view/Sandbox/TestPage2" while the external links are working as expected.

Environment: Windows 10, XWiki 11.10.4 with MySQL 5.7 and Chrome 80

![SVGExport](https://user-images.githubusercontent.com/40691112/78349562-766e8280-75ac-11ea-9fad-699df5a5b2c6.jpg)

**Comment by ane-gabriela** [comment]
Reproducing on XWiki 14.10.10 with Chrome 114. Diagram Application (Pro) 1.19

![InternalPages](https://github.com/xwikisas/application-diagram/assets/40691112/2cc36ee3-4028-4233-a761-d3cc46d243bc)

**Comment by ane-gabriela** [comment]
Tested on Cloud with XWiki 15.10.8 and also locally, with Diagram Application (Pro) 1.20.4 - it appears that the links to pages are working now, when exporting as SVG

![SGV15 10 8](https://github.com/xwikisas/application-diagram/assets/40691112/111c75cd-c951-4c2a-b066-af9cdbc52439)

**Comment by snazare** [comment]
thank you @ane-gabriela closing as the issue was fixed in the meantime.
