### ISSUE TITLE
The SVG isn't exported by default when doing a PDF export, although the property is in place

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#131]
Steps to reproduce:

1. Create a new Diagram
2. Add some shapes
3. Add a word in each shape
4. Select the word from one of the shapes
5. Click on the Link... button below Insert from the right panel
6. Select a wiki page > Apply
7. Click Save & View
8. Access More actions > Export > Export as PDF
9. Deselect all options > Export

Expected results: The diagram is exported as SVG, as after #102 this is the default selection (to also include links)

Actual results: The diagram is exported as png instead of SVG. When editing in object mode the SVG is correctly set.
The workaround is to just save the page in Object mode - without making any change and then the export works properly, exporting as SVG.

Environment: XWiki 11.10.4 with MySQL 5.7 and Chrome 81, Diagram Application (Pro) 1.13

![ObjectMode](https://user-images.githubusercontent.com/40691112/78988394-7a188100-7b39-11ea-91dd-ab59dbb3ff11.jpg)
[First Export - xwiki_Diagram_Admin+Diagram_WebHome.pdf](https://github.com/xwikisas/application-diagram/files/4461355/First.Export.-.xwiki_Diagram_Admin%2BDiagram_WebHome.pdf)

**Comment by mflorea** [comment]
Looks like an issue with choosing the default value when the ``exportUsingSVG`` is not specified. Should default to true (SVG export).

**Comment by ane-gabriela** [comment]
Reproduced also on XWiki 9.11, Chrome 81
