### ISSUE TITLE
Can't "Save & View" a diagram on IE 11

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#134]
Steps to reproduce:

1. Create a new diagram with some shapes
2. Click on Save & View

Expected results: The diagram is saved.

Actual results: The Save & View button becomes disabled but the page remains blocked and nothing happens, the page is not saved.

Environment: XWiki 11.10.4 with MySQL 5.7 and IE 11, Diagram Application (Pro) 1.13 

![IE11Save View](https://user-images.githubusercontent.com/40691112/79158578-3fd00d80-7ddf-11ea-8dc6-b5772f87633f.jpg)

**Comment by oanalavinia** [comment]
**Note** that I have opened a more general issue #144 that is valid for other browsers as well. Closing this issue separately since there were specific cases for IE
