### ISSUE TITLE
If you install XWebIDE Application you can't use "W" letter in the diagram text

### ISSUE THREAD

**Issue by iuliabalan** [xwikisas/application-diagram#15]
Steps:
* install Diagram and XWebIDE Application
* then create a diagram page
* edit the diagram and write some text, then try to type W
Result:
* the W letter is not typed, you can't save changes 
* you get redirected to a XWebIDE DefaultProject page

<img width="848" alt="screen shot 2018-11-30 at 9 29 40 am" src="https://user-images.githubusercontent.com/17314276/49275548-42e58a80-f484-11e8-87a4-31ec71c9930a.png">

<img width="798" alt="screen shot 2018-11-30 at 9 49 27 am" src="https://user-images.githubusercontent.com/17314276/49276935-98bc3180-f488-11e8-92e5-eefb175e61cf.png">

<img width="1162" alt="screen shot 2018-11-30 at 9 29 56 am" src="https://user-images.githubusercontent.com/17314276/49276958-ae315b80-f488-11e8-9b9a-b5940066f3f4.png">

**Notes:** 
* tested with Firefox 63.0.3 and Chrome 70.0.3538.102
*  the conflict comes from the XWebIDE App installed, for which W is a shortcut from XWiki (see https://extensions.xwiki.org/xwiki/bin/view/Extension/XWebIDE%20Application#HShortcuts)
 ** the issue is reproducing only when XWebIDE app is installed
 ** after uninstalling XWebIDE app the issue no longer reproduces

**Comment by mflorea** [comment]
@iuliabalan you should report this on the XWebIDE extension. They should either make the shortcut configurable or change the default shortcut. From the issue title I assume the shortcut is ``Shift+w``, which is a really bad choice from usability point of view..
