### ISSUE TITLE
PDF export from a diagram page in edit mode is exporting the Draw.io logo instead of the requested diagram

### ISSUE THREAD

**Issue by AndreeaChi** [xwikisas/application-diagram#175]
Hi team!

This issue was reproduced on a local Jetty XWiki 13.0 (and on a Docker container, still XWiki 13.0 version), Diagram Pro version 1.15.4 .

Steps to reproduce:
1. Edit a diagram and choose to export it as a PDF:
![image](https://user-images.githubusercontent.com/36840106/109026339-50703600-76c8-11eb-88d8-159338dcc3e7.png)
2. Picked one option (Selection or Crop or Grid, the result is the same with all options). 
3. Either Open in New Window or Download.
![image](https://user-images.githubusercontent.com/36840106/109026730-b9f04480-76c8-11eb-8aec-5d520a741975.png)
4. The result is 
![image](https://user-images.githubusercontent.com/36840106/109026785-c83e6080-76c8-11eb-8eec-a2e30dfa70f4.png)

The result is the same in full page mode or when I choose the PDF option from Advanced mode as well.

The diagram is exported when choosing the export as PDF option from the XWiki page menu.

In case the diagram I tested with could be useful, here it is a xar export of it in a zip (as this one was supported by git at upload):

[Diagram.project-organization-team.WebHome.zip](https://github.com/xwikisas/application-diagram/files/6037199/Diagram.project-organization-team.WebHome.zip)

Thank you for your help!

**Comment by mflorea** [comment]
@AndreeaChi have you tested with other diagrams? Are you able to export a very basic diagram that has for instance a single shape?

**Comment by oanalavinia** [comment]
@mflorea I just tested and it seems to be the same result even for a simple diagram

**Comment by oanalavinia** [comment]
The export from the diagram page uses an external service from draw.io and the url for this is the Diagram configuration page. The issue is caused by the fact that draw.io moved to diagrams.net space, so the export url that we provided was also changed.

Note that the fix can also be manually applied from _Global Administration > Other > Diagrams_  by adding https://convert.diagrams.net/node/export as _Export URL_

**Comment by gtothill** [comment]
Thanks all - this was one that I reported - the new API URL works fine.
All the best,
Geoff.
