### ISSUE TITLE
On page print via Ctrl+P, diagrams do not get resized to page width in Chrome

### ISSUE THREAD

**Issue by slauriere** [xwikisas/application-diagram#179]
## Steps to reproduce

1. Create a diagram
2. Add a rectangle to it, with a width of approximately 1200 pixels
3. Save and view the page
4. Hit Ctrl+P

## Actual result

* In Firefox, the diagram gets resized to the page width (see capture below)
* In Chrome, the diagram is cropped, hence only the first part of the rectangle is visible

### Diagram page

![diagram-page](https://user-images.githubusercontent.com/1022195/113268466-b22f4b80-92d7-11eb-91f3-7d88d2418d89.jpg)

### Diagram page print preview on Chrome

![diagram-print-chrome](https://user-images.githubusercontent.com/1022195/113268470-b2c7e200-92d7-11eb-83fa-a62e99d617f8.jpg)

### Diagram page print preview on Firefox

![diagram-print-firefox](https://user-images.githubusercontent.com/1022195/113268472-b3607880-92d7-11eb-85dd-d0a49d92d156.jpg)

## Expected result

* In Chrome, the diagram should get resized

## Workaround

Bypassing the dynamic sizing mechanism of the application by displaying the diagram as an image pointing at the generated SVG file allows to obtain the expected result on Ctrl+P on Chrome (an option is then to include that `img` element in the standard diagram sheet with a `@media print` rule displaying it only on print, while the diagram viewer should then get hidden on print (`class="hidden-print"`)).

```
{{html clean="false"}}
<img src='/xwiki/bin/download/Diagram/ABC/WebHome/diagram.svg' />
{{/html}}
```

### Diagram print preview on Chrome with workaround

![diagram-print-chrome-workaround](https://user-images.githubusercontent.com/1022195/113268941-3e417300-92d8-11eb-82ce-e29928018ba4.jpg)

## Environment

* Diagram Pro 1.15.5
* Latest Chrome and Firefox
* XWiki 13.0
* Ubuntu 20

## See also

* #178

**Comment by oanalavinia** [comment]
The problem seems to be that for Chrome the page is not scaled automatically at print step. On Firefox, the setting _"Fit to page width"_ is set by default.
Such a setting is not present on Chrome, but you can set _Settings -> More settings -> Scale_ to a _Custom_ width, with the value 89 for example, and this will lead to the same result as in the other browser.
Note that this scale will be available for all prints until it is changed back.
