### ISSUE TITLE
Create a migration script for diagrams affected by #11

### ISSUE THREAD

**Issue by oanat** [xwikisas/application-diagram#18]
While the issue #11 will be fixed for the future, we need a migration script for existing versions (e.g. users who would like to benefit of the latest version of the app until #11 is fixed)

**Comment by slauriere** [comment]
The migration script I intend to write will update the paths containing the old version name with the new one, for example : 


```
<mxCell id="6" value="" style="shape=image;html=1;verticalLabelPosition=bottom;labelBackgroundColor=#ffffff;verticalAlign=top;imageAspect=1;aspect=fixed;image=/xwiki-10.8/webjars/wiki%3Adev/draw.io/6.5.7/img/clipart/Gear_128x128.png" parent="1" vertex="1">
```

will get updated to:


```
<mxCell id="6" value="" style="shape=image;html=1;verticalLabelPosition=bottom;labelBackgroundColor=#ffffff;verticalAlign=top;imageAspect=1;aspect=fixed;image=/xwiki-10.8/webjars/wiki%3Adev/draw.io/8.9.9/img/clipart/Gear_128x128.png" parent="1" vertex="1">
```

**Comment by slauriere** [comment]
I created a script and I submitted it as a pull request #19. I tested it for an upgrade to the 1.6.1 pro version in the main wiki. NB: the script will work only for an upgrade to a pro version for now.

**Comment by slauriere** [comment]
PS: the script has to get executed after the upgrade, not before, as it migrates the image paths to the draw.io version that is currently installed.

**Comment by mflorea** [comment]
@slauriere if you access the Diagram home page before requesting a license you see this:

> Failed to execute the [include] macro. Cause: [Current user [xwiki:XWiki.Admin] doesn't have view rights on document [Document xwiki:Diagram.MigrationScriptMacros]]. Click on this message for details.

And below:

> There is no valid license for Diagram Application (Pro). Please visit the Licenses section.

The user should see only the last message. The include of ``MigrationScriptMacros`` should be done only if there is a valid license (inside the else of the ``IF`` that shows the above message). We need a new issue for this.

**Comment by slauriere** [comment]
Right, I created #34 to follow up on the issue that you raised, Marius.
