### ISSUE TITLE
No error is shown to the user when saving the diagram as SVG or PNG fails

### ISSUE THREAD

**Issue by slauriere** [xwikisas/application-diagram#186]
## Steps to reproduce

* Reduce maximum upload size in the current wiki:
  * On page `XWiki.XWikiPreferences`, edit object `XWiki.XWikiPreferences`
  * Set `Maximum Upload Size` field value to `1`
* Create diagram
* Add a shape to it
* Hit the `Save` button

## Expected result

* The generated SVG and PNG cannot be stored as attachments since their size exceeds the maximum upload size, so a warning or an error should be shown to the user about the fact the generated images could not be stored.

This expected result assumes that all diagram pages should have either a SVG or a PNG attachment - as an application feature - which seems to be the case indeed since `DiagramViewSheet` expects such an attachment on export.

## Actual result

* Only a success notification is shown with the message "Saved", with no feedback about the generated images storage error.

**Comment by slauriere** [comment]
Handling a possible `fail` of the promise returned by `saveFilesAsImageAttachments` in `DiagramEditSheet` would fire the display of the expected error:

```
saveFilesAsImageAttachments().fail(function(e) {
    new XWiki.widgets.Notification(
      $jsontool.serialize($services.localization.render('diagram.editor.saveAsImageAttachmentError')), 'error');
 }).always(function() {
    saveButton.prop('disabled', false).click();
 });
```

Ready to push this small change to master upon approval unless a pull request is more appropriate.

**Comment by mflorea** [comment]
@slauriere please create a PR. Thanks.
