### ISSUE TITLE
License is not recognized while upgrading diagram

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-diagram#196]
While upgrading Diagram from version 1.16.0 to 1.16.1 the license is not recognized. (XWiki 12.10.6)
![Screenshot from 2021-05-25 19-13-01](https://user-images.githubusercontent.com/12369283/119532842-ed0ca780-bd8d-11eb-9650-48f7f7426661.png)
![Screenshot from 2021-05-25 19-15-54](https://user-images.githubusercontent.com/12369283/119532856-f0079800-bd8d-11eb-82f2-a190b9e96069.png)

The licenses of other application are not recognized either.

This issue can be a temporary blocker if there is a XWiki Pro license, because of the pop-up.

The license is recognized again after the installation completed.

**Comment by mflorea** [comment]
@CamiAndrei I don't reproduce. This is what I did:

* I installed Diagram Application (Pro) 1.16 on XWiki 13.4
* I asked for a trial license
* I upgraded Diagram Application (Pro) to 1.16.1

The license was fine afterwards. I really don't see how upgrading Diagram Application (Pro) (and only that as the screenshot with the upgrade plan shows) can break the license.

Note that your first screenshot shows that you have installed Diagram **1.16** not **1.16.1**. Is this screenshot taken after the upgrade? Would be good to provide the exact steps to reproduce the problem. Thanks.

**Comment by CamiAndrei** [comment]
Hi! @mflorea The issue is present only for the time the application is upgrading. Yes after the upgrade is completed the license is recognized again.The screenshots are taken during the upgrade of the extension, not before, not after.
Steps to reproduce:
* I installed Diagram Application (Pro) 1.16 on XWiki 13.4
* I asked for a trial license
* I upgraded Diagram Application (Pro) to 1.16.1, but not completely. At this step the license was not recognized anymore:
![Screenshot from 2021-05-25 19-15-54](https://user-images.githubusercontent.com/12369283/119626547-048e7380-be14-11eb-9b6b-3e2ae7ed2306.png)\
See:
![Screenshot from 2021-05-25 19-13-01](https://user-images.githubusercontent.com/12369283/119626697-27b92300-be14-11eb-86f1-ba3810203e90.png)
But after the upgrade was completed the license was recognized again.

I hope now it's more clear. 

It may not be a big issue,  but it may cause confusion among users that use the wiki while the extension is upgrading.

**Comment by mflorea** [comment]
@CamiAndrei I still cannot reproduce. I followed your steps but the Diagram license was fine after the upgrade plan was computed, before executing the upgrade plan. I really don't see how the upgrade plan can break the license. There must be something else that triggered the issue.
