### ISSUE TITLE
Missing French Translation

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#20]
Preconditions: Have a FR wiki

1. Steps to reproduce:
2. Create a new Diagram
3. In Edit mode click on the plus (+) sign > "Inserer une image..."
4. Drag an drop a large image
5. Observe the message that appears

Expected results: All text appears in French.

Actual results: Some text appears in English.

![engtextinfrwiki](https://user-images.githubusercontent.com/40691112/53350755-6f486000-3928-11e9-979f-e62136079bf7.jpg)

![smile_-_pooh_b9b622d6](https://user-images.githubusercontent.com/40691112/53350718-5f308080-3928-11e9-85e6-a14abe26e240.gif)

**Comment by CamiAndrei** [comment]
This translation is missing from jgraph/draw.io library. The missing translation can be found here: https://github.com/jgraph/drawio/blob/77621cc93d8538255b0acc1d7c76adfedcf4ddb8/src/main/webapp/resources/dia_fr.txt . Seems that translations can be added here: https://docs.google.com/spreadsheets/d/1FoYdyEraEQuWofzbYCDPKN7EdKgS_2ZrsDrOA8scgwQ/edit#gid=0 and they will appear in the next release of  jgraph/draw.io .

**Comment by mflorea** [comment]
The ``resizeLargeImages`` key is still not translated in French in draw.io version 12.0.0.

**Comment by surli** [comment]
I just opened a PR on draw.io (https://github.com/jgraph/drawio/pull/593) to translate the key since the Google Doc @CamiAndrei posted seems to be only on readonly, we'll if it's enough to get the translation in next release.

**Comment by oanalavinia** [comment]
Tested with draw.io version 12.3.3 and the translation was added
