### ISSUE TITLE
Styles, font and text colors aren't showing as added by the user in the XWiki PDF export

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#213]
Steps to reproduce:

1. Create a new Diagram
2. Add some shapes eg. Textbox, Rounded Rectangle, Circle, Cylinder
3. Add some text in each one of them
4. Select a peace of text and make it bold
5. Select other pieces of text and select one style for each of them: italic, underline, strikethrough, different font, different text size, different text color, subscript, superscript 
![DiagramCreated](https://user-images.githubusercontent.com/40691112/143425530-c74646bd-9d62-4376-86f1-c55eb5b3d8f8.jpg)
3. Click Save & View
4. Access More actions > Export > Export as PDF
5. Deselect all options > Export

Expected results: The PDF looks like the diagram.

Actual results: Some styles aren't shown at all, some brake the paragraphs. 
![Comparison](https://user-images.githubusercontent.com/40691112/143426700-90369fa8-dddf-4558-b6b9-a439c1076678.jpg)

[xwiki_Diagram_Diagram+4_WebHome.pdf](https://github.com/xwikisas/application-diagram/files/7602171/xwiki_Diagram_Diagram%2B4_WebHome.pdf)

NOTE: While exporting the diagram through the Diagram menu (File > Export as > PDF... > Export) the PDF looks like the diagram created.
[export (1).pdf](https://github.com/xwikisas/application-diagram/files/7602173/export.1.pdf)

Environment: Windows 10, XWiki 13.4.5, Chrome 96, Diagram Application (Pro) 1.17.1

**Comment by ane-gabriela** [comment]
This is also affecting https://github.com/xwikisas/application-diagram/issues/153

[xwiki_Diagram_Diagram+1_WebHome.pdf](https://github.com/xwikisas/application-diagram/files/7602941/xwiki_Diagram_Diagram%2B1_WebHome.pdf)

**Comment by snazare** [comment]
not reproducing on xwiki 15.10.10, diagram pro 1.20.5, probably due to recent improvements.
