### ISSUE TITLE
Text position is changed in XWiki PDF Export, and some text doubled

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#218]
Steps to reproduce

1. Create a new Diagram
2. Add some shapes
3. Add some text in each one of them
4. Click Save & View
5. Access More actions > Export > Export as PDF
6. Deselect all options > Export

Expected results: The PDF exported shows the same Diagram as in View mode.

Actual results: Text appears top aligned and is some cases it is also doubled. 
![Exports](https://user-images.githubusercontent.com/40691112/145118251-3623cdac-7dbf-4741-81b3-5d9d4a96da18.jpg)

Note: While exporting PDF using the Diagram Menu, the shapes and text are shown as added by the user.

**Comment by petrenkonikita112263** [comment]
I can't reproduce the issue on local v14.10.8 with the latest version of app v1.19. I created some figures and put random text with block alignment. Then exported as PDF without ToC, footer/header - simple blank page. And the text alignment isn't doubled, and the position is saved.

![image](https://github.com/xwikisas/application-diagram/assets/56109799/c8ea1215-2d83-48bb-893f-38d10b3d08f1)

![image](https://github.com/xwikisas/application-diagram/assets/56109799/3c0e24a3-bb74-4da7-bcf6-30e704b056a3)

**Comment by snazare** [comment]
can not reproduce on XWiki 15.10.10 Diagram Pro 1.20.5
