### ISSUE TITLE
Issues with exporting Clipart shapes

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#22]
Steps to reproduce:

1. Add some Clipart shapes in a diagram
2. Export it as PDF, HTML, XML

Expected results: The shapes added are exported and shown.

Actual results: The Clipart shapes aren't appearing.

Environment: Windows 10, XWiki 10.11.3 with MySQL 5.7 and Edge 18

![htmlexportclipart](https://user-images.githubusercontent.com/40691112/53427961-91a6b000-39f2-11e9-8c13-7097c0711902.jpg)
![clipartdiagram](https://user-images.githubusercontent.com/40691112/53427963-91a6b000-39f2-11e9-9558-32186db78219.jpg)
![pdfexportclipart](https://user-images.githubusercontent.com/40691112/53427965-979c9100-39f2-11e9-9345-1c280b8876ff.jpg)

**Comment by arcilli** [comment]
Seems like the problem (or at least for HTML) is caused by bad URLs that are generated at export (a combination between draw.io & local instance of xwiki paths).

Now, depending of the use-case, would it be useful to provide a local URL (from local instance of xwiki) or URLs for draw.io hosted cliparts?  
WDYT, @mflorea?

**Comment by mflorea** [comment]
@arcilli can you post an example of an HTML export of a simple diagram with just a single clipart shape? (in order to better understand the issue). Thanks.

**Comment by arcilli** [comment]
`<g transformOrigin="0 0" transform="scale(1,1)translate(-102,-82)"><g></g><g><g style="visibility: visible;"><image x="110" y="90" width="80" height="80" xlink:href="https://www.draw.io/xwiki/webjars/wiki%3Asub/draw.io/8.9.9/img/lib/clip_art/networking/Bridge_128x128.png" style="pointer-events:none"></image><rect visibility="hidden" pointer-events="fill" x="110" y="90" width="80" height="80"></rect></g></g><g></g><g></g></g>`

Same problem with broken links is present when exporting diagrams with regular images (i.e. the images that are uploaded as attachments - image src example when exporting `https://www.draw.io/xwiki/wiki/sub/download/Diagram/A%20diagram/WebHome/Pim_batman-mask-clipart_273067.png`). Considering that, I'm thinking more about providing links from a local instance.

**Comment by mflorea** [comment]
Indeed, the URL

    https://www.draw.io/xwiki/webjars/wiki%3Asub/draw.io/8.9.9/img/lib/clip_art/networking/Bridge_128x128.png

is wrong. We need to find the place where this URL is generated and hook our code that uses the current host instead of ``draw.io`` (like we did for the URL export).

**Comment by ilieandriuta** [comment]
I don't know if it's the same cause, but neither JPEG files are exported in PDF (tested with Diagram Pro 1.7.1 on XWiki 11.3.3).

Diagram from XWiki page:

![Diagram_from_page](https://user-images.githubusercontent.com/32512703/64002938-e814b880-cb13-11e9-8865-83b5bfe59a1a.jpg)

Diagram exported as PDF:

![Diagram_exported_PDF](https://user-images.githubusercontent.com/32512703/64002967-f662d480-cb13-11e9-95c9-73fee564bd02.jpg)

Environment: Windows 10 Pro 64 bit, Chrome 76, using a local instance XWiki 11.3.3 on PostgreSQL 11

**Comment by mflorea** [comment]
@ilieandriuta is probably referring tot the PDF export from the Diagram menu, not the XWiki page export.

**Comment by ilieandriuta** [comment]
Yes, I was referring to JPEG files not being exported to PDF export from Diagram, basically following the Steps to reproduce listed above on this issue.

**Comment by arcilli** [comment]
@ilieandriuta, seems like that issue is already presented in #61.

**Comment by ane-gabriela** [comment]
Export as HTML was removed - see #53
