### ISSUE TITLE
Error in XWiki console when installing Diagram

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#224]
Steps to reproduce:

1. Install Diagram Application (Pro) 1.17.2 on XWiki 14.1

Expected results: The application is installed with no issues.

Actual results: The application is installed, but an Error appears in the XWiki console.

![DiagramError](https://user-images.githubusercontent.com/40691112/158400848-1c33c24d-c6ff-42dc-a689-4a3ce0625646.jpg)

Environment: Windows 11, Chrome 99, XWiki 14.1 with MySQL 8.0

**Comment by petrenkonikita112263** [comment]
I can't reproduce it on local 14.1 in MS Edge private window nor Google Chrome or Firefox's latest version. After the installation of v1.19, there's no NPE.

![IPOZR5y5Qd](https://github.com/xwikisas/application-diagram/assets/56109799/022b8312-e853-46f8-b024-9c7f379f04e7)

**Comment by snazare** [comment]
can not reproduce on 15.10.10, Diagram Pro 1.20.5
