### ISSUE TITLE
Mermaid import not working

### ISSUE THREAD

**Issue by jeppevinkel** [xwikisas/application-diagram#228]
Steps to reproduce:

1.  Create a new diagram
2. Insert Mermaid diagram via `Arrange->Insert->Advanced->Mermaid`
3. Click insert

After those steps it shows an error saying Mermaid isn't defined.
![image](https://user-images.githubusercontent.com/1492684/193559371-f5411ebb-a7ae-440b-9811-e4f616ed4e46.png)

Expected results: A diagram generated from the mermaid input.

**Comment by jeppevinkel** [comment]
Seems this error shows up on first attempt and then the above error on consecutive attempts.
![MicrosoftTeams-image](https://user-images.githubusercontent.com/1492684/193563713-4f49a2b9-96bd-4c9d-aeb1-96b6300ee6aa.png)

**Comment by snazare** [comment]
Reproduced on XWiki cloud 14.4.7 Diagram Pro 1.17.3

![image](https://user-images.githubusercontent.com/35834028/223381835-2d9ef428-5dbd-4a7d-b4a7-56fa34cc6c34.png)

**Comment by AndreeaChi** [comment]
The error still reproduces on Diagram Pro version 1.19.3, while trying to add the mermaid syntax:
`
graph TD
   A(Coffee machine <br>not working) --> B{Machine has power?}
   B -->|No| H(Plug in and turn on)
   B -->|Yes| C{Out of beans or water?} -->|Yes| G(Refill beans and water)
   C -->|No| D{Filter warning?} -->|Yes| I(Replace or clean filter)
   D -->|No| F(Send for repair)
`

from https://www.drawio.com/blog/mermaid-diagrams > flowchart type
<img width="803" alt="image" src="https://github.com/xwikisas/application-diagram/assets/36840106/72124c52-5e05-4503-8393-a5e8e62610c7">

**Comment by oanalavinia** [comment]
Note that mermaid import was added in drawio version [12.7.0](https://github.com/jgraph/drawio/commit/fe7dbdf9b6fe4c4d206da9e53590d9285676582a) and it never worked before in the Diagram Application.
