### ISSUE TITLE
XWiki 14.7/Diagram Application (Pro) 1.17.3 - Some Icons does not appear when viewing the diagram from the XWiki page

### ISSUE THREAD

**Issue by Stormrice** [xwikisas/application-diagram#229]
XWiki 14.7 
Diagram Application (Pro) 1.17.3 

**Step to reproduce**
1. Create a blank page
2. Add a diagram macro
3. Save the page
4. Clic on "create a diagram"
5. Type "switch" into the left search bar (icon)
6. Select the one with the double yellow/orange arrow in "S" shape (active directory library)

![image](https://user-images.githubusercontent.com/90713767/195645065-e3c24c2d-22ba-46fa-85ab-a9ed2345a0c7.png)

7. Add this icon to the diagram
8. Save and close
9. Jump back to the page
10. Here we can see that the diagram exists, but the icon does not appear
![image](https://user-images.githubusercontent.com/90713767/195644807-b0ab8d37-52a2-433d-8227-147a1a3f0786.png)

Thanks a lot :)

**Comment by snazare** [comment]
Can not reproduce on 14.4.7 Diagram Pro 1.17.3 : 

![image](https://user-images.githubusercontent.com/35834028/223381335-24ca9a1f-4733-4411-bd5c-b8d4eab60958.png)

Could you please offer additional details on the environment XWiki is installed in?

**Comment by snazare** [comment]
closing as inactive as I can not reproduce the issue.
