### ISSUE TITLE
If unregistered users have restricted access, importing images will break the cached diagrams

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-diagram#233]
**Prerequisites**: Have the following rights set:
![image](https://user-images.githubusercontent.com/22794181/218705591-ab75bb3c-e1ff-4932-b9b2-c8b4dec868a9.png)

**Steps to reproduce:**
1. Create a new diagram or edit an existing one
2. Insert an image using the ` + ` button -> `Image...` -> `Open` / `Drag and drop`
3. Save the diagram
4. Observe the attachments

**Expected result:** the image was added as attachment and the resulted `diagram.svg` and `diagram.png` are correct
**Actual result:** the image was added as attachment, but it's missing from `diagram.svg` and `diagram.png` 

If I add a _svg image_:
![image](https://user-images.githubusercontent.com/22794181/218710011-3b25cfb4-0b35-419c-b446-de5ad55567d7.png)
If I add a _png image_:
![image](https://user-images.githubusercontent.com/22794181/218710162-af3a3b69-de04-4bf9-a655-8bfdc916fc74.png)

Editing the diagram will not solve the problem

Tested with XWiki 13.10.6 and Diagram Application 1.17.2

**Comment by petrenkonikita112263** [comment]
After checking rights as mentioned, I can't reproduce issue. By inserting image (PNG, JPEG) format and saving diagram - image is present in attachment section alongside with original diagram files (SVG & PNG). 

It was checked with latest version v1.19.4 of app on XWiki v13.10

![image](https://github.com/xwikisas/application-diagram/assets/56109799/a0a3ad0b-2f67-48bc-97a1-b9a78ba557b6)

_Note_ image won't be saved in attachment section if user paste image via URL. I tried to insert this [image](https://unsplash.com/photos/selective-focus-photography-of-black-gemstones-ktVazL5c7FM) via URL and it's present in diagram. Example of [XAR](https://cryptpad.fr/file/#/2/file/WPLz88U6nk3KcCkgbsxJ2I93/).

**Comment by oanalavinia** [comment]
Indeed, the issue is reproducing on version 1.17.2, but not after upgrading to 1.19.4. Most probably it has been fixed by a drawio upgrade, so I'll close it as cannot reproduce
