### ISSUE TITLE
Confusing display of the current link in the "edit link" UI

### ISSUE THREAD

**Issue by lucaa** [xwikisas/application-diagram#234]
How to reproduce:
* create a text item in a diagram
* select the item and create a link
* from the link dialog, choose external link and type an external link in there:
![image](https://user-images.githubusercontent.com/657716/225281197-7ac8379b-bdd6-4dea-b53a-f5fdef6ecc3d.png)
* save and view the diagram - the link works as expected
* enter edit mode again
* select the text in the text element
* Edit the link:
  * choose Edit -> Edit Link
  * or click the link button in the "insérer" section in the Text settings on the right
  * or right click on the link itself and choose "edit link" from the contextual menu

Expected result:
* the link dialog should show the current state of the link:
  * the external tab should be selected
  * with the external link displayed
 
Actual result:
* the link selector popup display actually seems to depend on multiple factors but it rarely seems right:
  * by default, the "browse" tab of the link selector popup seems to be selected, with a page selected in it, even if we're editing an external link
    * sometimes the existing external link is not even displayed in the "External" tab input, but this happens mostly for links added in the text in the text box (for example, on parts of the text), for which is not even sure that we're actually editing the link itself
  * moreover, if another link is edited before the current one, the dialog seems to keep its previous state from the previous link instead of it reflecting the state of the current wiki

If the link is added on the text box itself and not on the text inside the box, there is a better display of the link allowing a clearer edit because it sports an edit button on selection:
![image](https://user-images.githubusercontent.com/657716/225284825-9a95ed5c-9816-4d78-b4f5-6731ab670f10.png)

However, the problems above of the link editing still persist.

As a conclusion, it can be hard and confusing to know what a link links to, especially when added on the text inside an element and not on the element itself, and if a user clicks "Apply" instead of "cancel" in the edit link dialog, they may actually be making changes to the links without knowing, as the dialog does not display a valid state.

Note: this ticket may need to be split in multiple tickets.

**Comment by oanalavinia** [comment]
The major cause of the confusion comes from the fact that when editing a link, the correct tab is not highlighted, and instead the last active one is displayed. So when switching  between `external` and `browse` tabs, it can get very annoying and lead to a lot of broken links.

The second part of the issue, related to editing links added to text, is actually a drawio bug https://github.com/jgraph/drawio/issues/3654 , so this won't be fixed as part of this issue
