### ISSUE TITLE
Background image isn't shown in the PDF Export

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#241]
Steps to reproduce:

1. Create a new diagram
2. In Edit mode tick the Background selection
3. Click on the Image button
4. Drag and drop an Image from local device
5. Add any shapes 
![BackgroundAndShapes](https://github.com/xwikisas/application-diagram/assets/40691112/a113e8aa-944b-481f-97b7-73ff163a911c)
6. Click on File > Export as > PDF... > Export > Download
7. Save the PDF to the local device
8. Open the PDF

Expected results: The diagram is exported as created.

Actual results: Instead of the background image only the icon for an image shows. 

![Reuslt](https://github.com/xwikisas/application-diagram/assets/40691112/8d335881-49d7-466f-a575-10054aef0247)

[Diagram 2.pdf](https://github.com/xwikisas/application-diagram/files/12049821/Diagram.2.pdf)

Environment: Windows 11, XWiki 14.10.10, Chrome 114, Diagram Application (Pro) 1.19

**Comment by ane-gabriela** [comment]
Can't retest this ticket at the moment because of issue https://github.com/xwikisas/application-diagram/issues/270

**Comment by snazare** [comment]
to be handled in #288
