### ISSUE TITLE
Can't import a Gliffy diagram

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#243]
Preconditions: Have a diagram exported from Gliffy on your devide.

Steps to reproduce:

1. Create a new diagram
2. Click on File > Import from > Device...
3. Select a Gliffy diagram > Open

Expected results: The Gliffy diagram is imported correctly.

Actual results: "Error
Unknown error" appears. The diagram is not imported.

![GliffyImport](https://github.com/xwikisas/application-diagram/assets/40691112/560218e3-e796-46f1-a92c-7f6d54c9010a)

Environment: Windows 11, XWiki 14.10.10, Chrome 114, Diagram Application (Pro) 1.19

**Comment by oanalavinia** [comment]
Caused by the upgrade to drawio version 20.5.0 in #223
