### ISSUE TITLE
Internal links don't appear in the PDF export created from the Diagram menu

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#244]
Steps to reproduce:

1. Create a new diagram with shapes that contain text
2. Select a word and link it to an internal page ex. Sandbox Test Page 1
3. Select a another word and link it to an external URL ex. https://store.xwiki.com/xwiki/bin/view/Main/WebHome
4. Click on File > Export as > PDF... > Export > Download
5. Open the resulted PDF
6. Click on the words with links

Expected results: The user is redirected to the selected page/URL.

Actual results: Only the external URL works when the text is clicked. The links to the internal pages don't appear in the PDF, the text is only blue and with underline.

[Diagram 1.pdf](https://github.com/xwikisas/application-diagram/files/12171396/Diagram.1.pdf)

![InternalExternalLinks](https://github.com/xwikisas/application-diagram/assets/40691112/8fdc5ff2-25b0-4d58-bed8-5c5de209ac93)

Environment: Windows 11, XWiki 14.10.10, Chrome 114, Diagram Application (Pro) 1.19

**Comment by lucaa** [comment]
Note: this pdf export feature is using an external service to perform the export, so it would be disabled (from administration) in quite a number of cases.

**Comment by snazare** [comment]
Handled in #288
