### ISSUE TITLE
Links in the diagram aren't updated when the linked pages are moved/renamed

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#245]
Steps to reproduce:

1. Create a page eg. Page 1
2. Create a diagram with shapes that contain text
3. Add a link on one of the text to Page 1
4. Move / Rename "Page 1" to "QA Test"
5. Access the diagram
6. Observe the link to the page 
![ResultAfterChange](https://github.com/xwikisas/application-diagram/assets/40691112/c5499c35-c838-4b40-b292-343195c7af3e)
7. Click on the link 

Expected results: The link to the page is updated with the new location and/or name. Related to https://github.com/xwikisas/application-diagram/issues/110

Actual results: The link to the page remains the same, it's not updated, which makes the user to be redirected to a non existing page.

![WhenClicked](https://github.com/xwikisas/application-diagram/assets/40691112/8c896b91-32bb-4026-b053-88c0877401fd)

Environment: Windows 11, XWiki 14.10.10, Chrome 114, Diagram Application (Pro) 1.19

**Comment by ane-gabriela** [comment]
Issue reproducing on Windows 11, Chrome 125. Cloud XWiki 15.10.8, Diagram Application (Pro) 1.20.4

**Comment by claudiuion117** [comment]
I reproduced the issue on Firefox 128.0.3., XWiki 15.10.8. on premise, Diagram App Pro 1.20.4.
A client also reported this problem on XWiki 15.10.8. on premise, Diagram App Pro 1.20.1.:https://jira.xwikisas.com/browse/XNSUPPORT-8812

**Comment by claudiuion117** [comment]
I reproduced this issue on Firefox 128.0.3. , XWiki 15.10.8. on premise with Diagram App Pro 1.20.4. and on  XWiki version 15.10.11. (LTS version)

**Comment by ane-gabriela** [comment]
Reproducing on Windows 11, XWiki 15.10.10, Chrome 128, Diagram Application (Pro) version 1.21-rc-1

**Comment by Farcasut** [comment]
This issue has two causes:
    https://github.com/xwikisas/application-diagram/issues/294
    https://github.com/xwikisas/application-diagram/issues/295

**Comment by ane-gabriela** [comment]
Issue still reproducing on Windows 11 PRO, XWiki 14.10.21, Diagram 1.22.0-rc-2, Chrome 131

![BeforeRenameMove](https://github.com/user-attachments/assets/895c5d52-cfed-4af8-a457-0a87ee2f4e42)

![Result](https://github.com/user-attachments/assets/eac1080a-6a81-4413-8b94-180fb54c52c6)

**Comment by Farcasut** [comment]
The issue occurred because draw.io had an additional method of storing the link in the XML elements, and we didn’t handle that case. If this issue happens again in the future, please also provide the content of the diagram (press K and copy-paste it).
