### ISSUE TITLE
Open editor in new window

### ISSUE THREAD

**Issue by larsnaesbye** [xwikisas/application-diagram#257]
Complex and large diagrams get tiny when they have to be edited in-place - this makes it impossible to edit properly.
It would be nice to be able to open the editor in a new window/tab without the menus etc.

**Comment by larsnaesbye** [comment]
It was apparently implemented in the non-Pro version: https://jira.xwiki.org/browse/XADIAGRAM-36

**Comment by snazare** [comment]
hi @larsnaesbye thank you very much for your report. Indeed i would tend to close this issue as the consensus within our team is to keep the editing mode in the same tab; also, full screen editing is now possible. Would that be ok with you?

**Comment by larsnaesbye** [comment]
All fine with me :)
