### ISSUE TITLE
Can't Import a diagram from Browser

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#26]
Preconditions: Have a diagram saved as Browser eg. go to draw.io, create a new diagram and save it as Browser.

Steps to reproduce:

1. Edit the diagram page
2. Click on File > Import from > Browser...

Expected results: A message box appears where the respective diagram can be selected and imported.

Actual results: No files appear.

Environment: Windows 10, XWiki 10.11.3 with MySQL 5.7 and Edge 18, Chrome 72

![nofilesfound](https://user-images.githubusercontent.com/40691112/53491619-85c4f780-3a9f-11e9-964b-911f09da08d2.jpg)

**Comment by arcilli** [comment]
This option is not anymore available, so I'm closing this issue.

**Comment by arcilli** [comment]
My bad seems like this option is still available on 1.7. Reopen this issue.
