### ISSUE TITLE
Comment editor missing options on diagram page

### ISSUE THREAD

**Issue by avision-it** [xwikisas/application-diagram#266]
If you add a comment to a diagram page, the editor (ckeditor) misses a lot of options in the toolbar that are visible on normal pages. There are no errors in the console. The options are just missing:

![image](https://github.com/xwikisas/application-diagram/assets/54308693/3ca5674a-dd06-42a9-be19-f0efa1691e36)

Regular comment:

![image](https://github.com/xwikisas/application-diagram/assets/54308693/d2a292dd-dc2c-4181-9465-9ec68490a5a8)

Xwiki version 15.10.8, Diagram Application Pro 1.20.4

I'm not sure if it's a configuration issue. It also happens on a test installation.

**Comment by snazare** [comment]
Hi @avision-it  thank you very much for your report! Indeed, this is a manner of configuration. The CKEditor in the Comments section is by default configured to feature less editing options than the one on the standard pages. Please refer to our [CKEditor integration documentation](https://extensions.xwiki.org/xwiki/bin/view/Extension/CKEditor%20Integration/#HAdministrationSection) to learn more about how to configure the editors in your XWiki instance.
