### ISSUE TITLE
Saving imported draw.io file fails

### ISSUE THREAD

**Issue by avision-it** [xwikisas/application-diagram#267]
Some imported draw.io files fail to save in a diagram page. I think it's related to embedded images or pdfs. Here's the screenshot if you click Save & View:

![image](https://github.com/xwikisas/application-diagram/assets/54308693/82d5c688-8948-4e11-aaf9-a8bb6f5bf696)

The page is empty afterwards and there are no attachments. The upload fails without further errors in the console or tomcat logs.

I've tested it on a fresh install and our production system.

 I've attached a test file that fails to save. Can you please look into this problem?

[Test_12224.zip](https://github.com/xwikisas/application-diagram/files/15348161/Test_12224.zip)

XWiki 15.10.8, Diagram Application Pro 1.20.4

**Comment by petrenkonikita112263** [comment]
Indeed, I can also reproduce by attempting the import not only your file, but any `drawio` file from [sample page](https://www.drawio.com/example-diagrams). However, if I use import from URL and put the full URL like this `https://raw.githubusercontent.com/jgraph/drawio-diagrams/dev/examples/uml-activity-example.drawio` after saving the diagram is present.

https://github.com/xwikisas/application-diagram/assets/56109799/393f32ec-0ad2-40ac-964b-b19d0ef0cb1b

**Comment by avision-it** [comment]
Hmm, i get one step further with Import from URL. But i still can't save the diagram. This error message occurs when saving:

![image](https://github.com/xwikisas/application-diagram/assets/54308693/d3f42148-8d4f-4344-ab8b-87c8e9262d9d)

But I'm not logged off and it's not an authorization problem. I'm clueless what could be the problem...

**Comment by oanalavinia** [comment]
This seems to be related to the implementation of the multiple pages feature in https://github.com/xwikisas/application-diagram/issues/250 , so it was introduced in version 1.22.3
Checking to fix the issue. Until then, a workaround would be to downgrade Diagram Application to an older version, e.g. 1.22.2
