### ISSUE TITLE
Can't save the XML diagram imported from Device

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#271]
Preconditions: Have a diagram page created with some added shapes.

Steps to reproduce:

1. Edit the diagram page
2. Click on File > Export as > XML...
3. Click on Export
4. Choose a name for the diagram
5. Click on Download
6. Create a new diagram or edit an existing one
7. Click on File > Import from > Device...
8. Browse the diagram from the device
9. Open it  ![OpenDiagramXML](https://github.com/xwikisas/application-diagram/assets/40691112/7e1a56c3-d8b5-4d0f-b621-51b401f02bf7)
10. Click on Save & View

Expected results: The XML diagram is imported and saved.

Actual results: A "Leave site?" message box pops up at the top of the screen 
![ClickingSaveView](https://github.com/xwikisas/application-diagram/assets/40691112/e65c3305-9df7-457b-a548-11c9af70963d)

After the user clicks on the Leave button nothing is saved
![ResultAfter](https://github.com/xwikisas/application-diagram/assets/40691112/88bc471a-cc71-44d7-8727-bd17b88c1340)

Environment: Windows 11, Chrome 125. Cloud XWiki 15.10.8, Diagram Application (Pro) 1.20.4

**Comment by sangdrax8** [comment]
I am seeing the same issue Diagram Application (Pro) 1.20.4

**Comment by oanalavinia** [comment]
Fixed by https://github.com/xwikisas/application-diagram/commit/7df66715566e50acc4235d2d2ee9947f8bcfcb57 , since it failed for the same reason
