### ISSUE TITLE
Downloading SVG makes links non functional

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#319]
Seems to be a regression for https://github.com/xwikisas/application-diagram/issues/130

Steps to reproduce:

1. Create a new Diagram
2. Add some shapes
3. Add a word in each shape
4. Select the word from one of the shapes
5. Click on the Link... button below Insert from the right panel
6. Select a wiki page > Apply 
![InternalPage](https://github.com/user-attachments/assets/c4c00a46-4fe9-4aa5-92ec-39ae5422344b)
7. Select another shape/word
8. Click on the Link... button below Insert from the right panel
9. Select External and paste an URL eg. https://en.wikipedia.org/wiki/Flower 
![ExternalLink](https://github.com/user-attachments/assets/04c02e7e-b80b-4329-a1ae-c3e70cf32397)

10. Click File > Export as > SVG...
11. Click on Export
12. Click on Download > Save
13. Open the SVG
14. Click on each of the links

Expected results: The links are showing as expected.

Actual results: When clicking on the link to the internal page it gives "javascript:void(0);" and the link to the external url doesn't work at all - it's just like text not a link.

![Heading](https://github.com/user-attachments/assets/1a6430af-5db6-4373-ac2b-9fc50b76febf)

Environment: XWiki 14.10.18 with Diagram version 1.21.1-rc-1, Chrome 131, Windows 11 Pro

**Comment by ane-gabriela** [comment]
Issue reproducing on XWiki 15.10.14, Chrome 131, Windows 11 Pro

**Comment by Farcasut** [comment]
The issue has been fixed, and everything should work as expected starting with version 1.22. To fix older diagrams(created in 1.21-1-rc-1) before exporting, resave them
