### ISSUE TITLE
Undefined translation key when the licence of the diagram app is not valid

### ISSUE THREAD

**Issue by aubincleme** [xwikisas/application-diagram#38]
When the diagram app has no valid license, the diagrams are replaced with an error macro with the a translated text under the key `diagram.app.noValidLicense`.

This key isn't defined.

**Comment by CamiAndrei** [comment]
@aubincleme What do you mean by "the licence of the diagram app is not valid"?
Was the license never added or the license expired? Is there an other way to obtain a invalid license?
I tested with no license added and I obtained #39 . 
Thanks.

**Comment by aubincleme** [comment]
Looking at the codebase, it seems that this translation key is actually defined somewhere in the app ([DiagramMacro, line 245](https://github.com/xwikisas/application-diagram/blob/6a0a9174668d263c7c6235ad148a51274df09d84/src/main/resources/Diagram/DiagramMacro.xml#L245)) and never translated : 

```
caubin@t580:~/Projects/xwiki/pro/application-diagram/src/main (master=) % grep -R -n -A 5 -B 5 "diagram.app.noValidLicense"
resources/Diagram/DiagramMacro.xml-240-## don't have view right on those pages.
resources/Diagram/DiagramMacro.xml-241-#if ($services.licensing.licensor.hasLicensureForEntity($xcontext.macro.doc.documentReference))
resources/Diagram/DiagramMacro.xml-242-  #executeDiagramMacro
resources/Diagram/DiagramMacro.xml-243-#else
resources/Diagram/DiagramMacro.xml-244-  {{error}}
resources/Diagram/DiagramMacro.xml:245:    {{translation key="diagram.app.noValidLicense" /}}
resources/Diagram/DiagramMacro.xml-246-  {{/error}}
resources/Diagram/DiagramMacro.xml-247-#end
resources/Diagram/DiagramMacro.xml-248-{{/velocity}}</code>
resources/Diagram/DiagramMacro.xml-249-    </property>
resources/Diagram/DiagramMacro.xml-250-    <property>
```

**Comment by aubincleme** [comment]
Looks like [the licensor app](https://github.com/xwikisas/application-licensing/blob/0163c1fa39d2cb62174be41201d6693922a7960a/application-licensing-licensor/application-licensing-licensor-ui/src/main/resources/Licenses/Code/Translations.fr.xml#L84) provides good translation keys when no license is available.

**Comment by aubincleme** [comment]
So @CamiAndrei, the error itself is shown when https://github.com/xwikisas/application-diagram/blob/6a0a9174668d263c7c6235ad148a51274df09d84/src/main/resources/Diagram/DiagramMacro.xml#L241 returns false, IE when the extension isn't licensed AFAICS.

**Comment by CamiAndrei** [comment]
This issue was fixed in https://github.com/xwikisas/application-diagram/commit/a08f72c452331f7fb89fee5cf8073df873df0b8c. It looks like you don't have the latest sources of the application.

**Comment by aubincleme** [comment]
@CamiAndrei unfortunately, the commit that you mentioned (a08f72c) is actually the source of the problem : 
* This removes the translation key : https://github.com/xwikisas/application-diagram/commit/a08f72c452331f7fb89fee5cf8073df873df0b8c#diff-035c5451da0f00adc26c2890518f977bL47
* This fixes one place where the translation key is, but not the one in the DiagramMacro (it's editing Diagram.WebHome) : https://github.com/xwikisas/application-diagram/commit/a08f72c452331f7fb89fee5cf8073df873df0b8c#diff-18d1947d68d444feb3d87b8da1cb24c4R70

> It looks like you don't have the latest sources of the application.

Apparently no :

```
caubin@millenium:~/Projects/XWiki/xwiki-sas/application-diagram/src (master=) % git log | head
commit 6a0a9174668d263c7c6235ad148a51274df09d84
Author: Alex Cotiugă <alexandru.cotiuga@xwiki.com>
Date:   Wed Apr 10 22:23:16 2019 +0300

    [maven-release-plugin] prepare for next development iteration

commit ce74f429d7ab2517fb8606fcf66c59a67afff58b
Author: Alex Cotiugă <alexandru.cotiuga@xwiki.com>
Date:   Wed Apr 10 22:23:16 2019 +0300

caubin@millenium:~/Projects/XWiki/xwiki-sas/application-diagram/src (master=) % grep -R -n -A 5 -B 5 "diagram.app.noValidLicense"
main/resources/Diagram/DiagramMacro.xml-240-## don't have view right on those pages.
main/resources/Diagram/DiagramMacro.xml-241-#if ($services.licensing.licensor.hasLicensureForEntity($xcontext.macro.doc.documentReference))
main/resources/Diagram/DiagramMacro.xml-242-  #executeDiagramMacro
main/resources/Diagram/DiagramMacro.xml-243-#else
main/resources/Diagram/DiagramMacro.xml-244-  {{error}}
main/resources/Diagram/DiagramMacro.xml:245:    {{translation key="diagram.app.noValidLicense" /}}
main/resources/Diagram/DiagramMacro.xml-246-  {{/error}}
main/resources/Diagram/DiagramMacro.xml-247-#end
main/resources/Diagram/DiagramMacro.xml-248-{{/velocity}}</code>
main/resources/Diagram/DiagramMacro.xml-249-    </property>
main/resources/Diagram/DiagramMacro.xml-250-    <property>
```

**Comment by aubincleme** [comment]
It's really an easy fix and maybe we shouldn't be wasting so much time on it. I'll make a PR at some point …

**Comment by CamiAndrei** [comment]
Thanks for the clarification.
