### ISSUE TITLE
When opening a diagram in wiki mode a fail message appears

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#60]
Steps to reproduce:

1. Create a new diagram
2. Open it in Wiki mode

Expected results: The diagram is opened in wiki mode.

Actual results: The diagram is opened but a fail message appears at the bottom of the page.
This only happens when the user opens the diagram in wiki mode the **First** time. If the page is closed and open again the message doesn't appear anymore.

![DiagramOpenInWikiMode](https://user-images.githubusercontent.com/40691112/63854627-3d32bc00-c9a6-11e9-9d4e-e02c4cec2fe3.jpg)

Environment: Windows 10, XWiki 11.3.3 with MySQL 5.7 and Chrome 76

**Comment by mflorea** [comment]
You get the same message when you edit a translation page. The reason is because the syntax used by the diagram page **plain/1.0** (as well as any translation page) is not supported by the Syntax Highlighting application, which is fine. So it's not specific to the Diagram Application.
