### ISSUE TITLE
The Export as URL > Copy button is missing on IE 11

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#65]
Steps to reproduce:

1. Edit a diagram
2. Click on File > Export as > URL... > Create

Expected results: All the buttons are as required, same on all browser.

Actual results: On IE 11 the Copy button is missing. It appear on Edge 18, Chrome 76 and Firefox 69.

![CopyButtonMissing](https://user-images.githubusercontent.com/40691112/64411653-5fa79200-d096-11e9-9762-e2b064f31a76.jpg)

**Comment by mflorea** [comment]
The same happens on draw.io . The Copy button is hidden on IE11 on purpose, because clipboard access is restricted on IE11 for security reasons.
