### ISSUE TITLE
Issues with inserting links to wiki pages

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#73]
Tested on XWiki 8.4.5, 11.3.4 and 11.7 and the Internal link can be added on a specific text but **after Save & View, nothing happens when the link is clicked**. It works for external links.

On Cloud (10.11.9) it seems the Internal link can't be added at all - after selecting to link to a specific page from the picker, **nothing happens when clicking the Apply button**. The external link works.

Regarding #64 

![CloudApply](https://user-images.githubusercontent.com/40691112/65505424-dc799f00-ded1-11e9-8cb9-98acc35be8b0.jpg)

**Comment by mflorea** [comment]
For the first problem (click on links in view mode) I can see the problem, I'll work on it. For the second problem, you need to give more details as I can't reproduce on my local instance. There must be something special with the cloud instance. Was there any JavaScript exception logged in the console on the cloud? Do you have a link where I can reproduce?

**Comment by ane-gabriela** [comment]
The second issue I reproduced only on Cloud, not on local instances. I don't get anything new when I click the Apply button, the info in the console appears when I edit the Diagram
![Save ViewInternalLink](https://user-images.githubusercontent.com/40691112/65950230-549e1280-e446-11e9-8205-8a4eb2f09f85.jpg)

I used  https://gabybasic.demo-staging.infra-staging.devxwiki.com/xwiki/bin/view/Main/
