### ISSUE TITLE
Diagram element is moved away from its position when colored

### ISSUE THREAD

**Issue by silviamacovei** [xwikisas/application-diagram#75]
To reproduce please create a Diagram and change the color of an element. You will notice that at the moment you change the color, the element moves slightly from its initial position. This leads to the user having to reposition the element in its original place.

![ColorElement](https://user-images.githubusercontent.com/42776453/66127619-c9af4a80-e5f4-11e9-826c-c1c4604359ee.gif)

**Comment by mflorea** [comment]
Doesn't reproduce on draw.io so it's an integration bug. The workaround for now is to hide the horizontal and vertical ruler from the ``View > Ruler`` menu. The shapes are redrawn as if the ruler is not present so they shift with the rule width. I'm looking for a fix.

**Comment by mflorea** [comment]
This issue is a regression caused by the recent draw.io upgrade.
