### ISSUE TITLE
The license of the Diagram is not applyed after upgrade

### ISSUE THREAD

**Issue by CamiAndrei** [xwikisas/application-diagram#77]
Steps to reproduce:
1. Install Diagram Application, an older version, 1.8 for example
2. Get a license 
3. Create a Diagram
4. Upgrade the Diagram Application to 1.9 version
5. The license seems to be invalidated ( a message of no valid license is displayed)

Expected results:
The license is applied after upgrade
Actual results:
A message of no valid license is displayed.

**Comment by mflorea** [comment]
The license is found if you restart XWiki.

**Comment by CamiAndrei** [comment]
Or if you click Check for updates, but it's confusing for a nontechnical user to see that his Diagrams disappeared.

**Comment by mflorea** [comment]
The reason is this https://up1.xwikisas.com/#JsVs6eAYjZ_VYza6u9HjkQ .

**Comment by mflorea** [comment]
@tmortagne if you want to debug, here's what I did to reproduce the issue:

* I took a clean XWiki 11.8
* installed Diagram Application Pro 1.8
* got a trial license
* created a diagram page

At this point it's useful to backup the ``data`` folder.

* I upgraded Diagram to version 1.9. Look at the end of the progress log. There's a warning with a stack trace there.

The issue reproduces also if you:

* stop XWiki at this point
* put the backup of the ``data`` folder
* do one of these:
** view a diagram page
** or edit a plain wiki page (either wiki or WYSIWYG)
** view the home page (if the tour was not skipped already)
* then upgrade Diagram to version 1.9

The issue doesn't reproduce if you:

* stop XWiki
* put the backup of the ``data`` folder
* go directly to the Extension Manager and upgrade the Diagram to version 1.9

Note that I modified the ``ResourceLoader`` to log the path of the jars that fail to be read and the path is different depending on what you do before the upgrade, but it was always a **WebJar**:

* /data/extension/repository/org%2Ewebjars%3Acodemirror/5%2E24%2E2/org%2Ewebjars%3Acodemirror-5%2E24%2E2.jar
* /data/extension/repository/org%2Exwiki%2Econtrib%3Amxgraph-client/4%2E0%2E4_11%2E2%2E9/org%2Exwiki%2Econtrib%3Amxgraph-client-4%2E0%2E4_11%2E2%2E9.jar
* /data/extension/repository/org%2Exwiki%2Econtrib%3Amxgraph-editor/4%2E0%2E4_11%2E2%2E9/org%2Exwiki%2Econtrib%3Amxgraph-editor-4%2E0%2E4_11%2E2%2E9.jar
* data/extension/repository/org%2Exwiki%2Econtrib%3Adraw%2Eio/11%2E2%2E9/org%2Exwiki%2Econtrib%3Adraw%2Eio-11%2E2%2E9.jar

**Comment by mflorea** [comment]
@CamiAndrei was your XWiki instance running on Jetty or Tomcat?

**Comment by CamiAndrei** [comment]
Hi! I have reproduce this with a cloud instance 9.11.3  and with a local instance 8.4 with Jetty

**Comment by ilieandriuta** [comment]
Hi! I've tested on XWiki 11.8.1 on Tomcat by upgrading from Diagram 1.8 to 1.9 and I couldn't reproduce the issue.  Environment: Windows 10 Pro 64bit, Chrome 77, HSQL 2.5.0/ Tomcat 9.0.16 distribution.

**Comment by CamiAndrei** [comment]
On the other hand I have tested on 11.8.1 on Jetty, after upgraded the app from 1.8 to 1.9 the license was valid but the Diagrams didn't load. Spinning wheel was displayed.
