### ISSUE TITLE
Cliparts aren't showing properly after upgrade from 1.10 to 1.11

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#90]
After upgrading the Diagram app from v 1.10 to 11.11 the Clipart shapes aren't appearing properly anymore.

Environment: Windows 10, Chrome 78, XWiki 11.3.6 and 8.4.5

![DiagramV1 10](https://user-images.githubusercontent.com/40691112/69801403-d2c92c00-11df-11ea-9f0f-a97455a54ab9.jpg)

![ClipartAfterUpgrade](https://user-images.githubusercontent.com/40691112/69801425-dceb2a80-11df-11ea-8af0-f5034317df58.jpg)

**Comment by oanalavinia** [comment]
Related to #11
