### ISSUE TITLE
The link to a wiki page isn't working in Print Preview after upgrade from v 1.10 to 1.11

### ISSUE THREAD

**Issue by ane-gabriela** [xwikisas/application-diagram#92]
The links that are created with v 1.10 or the ones created with 1.11 after the upgrade aren't working in Print Preview. When the link is clicked a download starts.

Environment: Windows 10, Chrome 78, XWiki 11.3.6 and 8.4.5

![Downloads](https://user-images.githubusercontent.com/40691112/69802746-e75af380-11e2-11ea-8bc9-c0fa8483ddf1.jpg)

**Comment by mflorea** [comment]
Duplicate of #88.
