### ISSUE TITLE
Update parent version to 9.11

### ISSUE THREAD

**Issue by acotiuga** [xwikisas/application-diagram#97]

**Comment by mflorea** [comment]
The places that would have to be updated:

* https://github.com/xwikisas/application-diagram/blob/application-diagram-1.12.2/application-diagram-api/src/main/java/com/xwiki/diagram/internal/DiagramApplicationListener.java#L68
* https://github.com/xwikisas/application-diagram/blob/application-diagram-1.12.2/application-diagram-api/src/main/java/com/xwiki/diagram/internal/DrawIOImagePathMigration.java#L61
* https://github.com/xwikisas/application-diagram/blob/application-diagram-1.12.2/application-diagram-api/src/main/java/com/xwiki/diagram/internal/StoreSVGAsAttachmentMigration.java#L64
