### ISSUE TITLE
Background images are not visible after import

### ISSUE THREAD

**Issue by oanalavinia** [xwikisas/application-diagram#99]
**Steps to reproduce:**

1. Create a new diagram
2. Select a background image
3. Add some shapes, text
4. Click Save or Save & View
5. Click on File > Export as > XML > Export
6. Create a new diagram
7. Click on File > Import from > Device
8. Select the new exported diagram > Import

**Expected results:** 
The diagram appears just like in the source diagram (with the shapes, text and the background image).

**Actual results:** 
The background image is missing.

**Comment by oanalavinia** [comment]
I did a test on www.draw.io and it seems that ATM this is not working.
I have created an issue on their side https://github.com/jgraph/drawio/issues/679

**Comment by snazare** [comment]
closing and continuing on #242
